.\"Manpage for lainsafe
.TH clainsafecli 1
.SH NAME
clainsafecli \- File uploader

.SH DESCRIPTION

clainsafecli is a file uploader. Intended for lainsafe, but also works
for 0x0.st, i.kalli.st and probably others.

.SH INSTALLATION
.in +4n
.EX
make
(or gcc clainsafecli.c -lcurl -o clainsafecli)
cp clainsafecli ~/.local/bin
.EE
.SH OPTIONS

.PP
.B
--server=<SERVER>
Specifies which server to use, can be a lainsafe instance, 0x0.st
instance or i.kalli.st. Probably other similar software.

.B
--tor
Routes all the traffic on the socks proxy at 127.0.0.1:9050,
which is usually tor. This can be edited in the
.B options.h
file

.B
--i2p
Routes all the traffic on the http proxy at 127.0.0.1:4444,
which is usually I2P. This can be edited in the
.B options.h
file

.B
--ipv6 or -6
Forces curl to use IPv6 only.

.B
--ipv4 or -4
Forces curl to use IPv4 only.

.B
--silent or -S
tells clainsafecli to be silent. This means, it won't
print the progress.
